- name: Déploiement de l’application Next.js
  hosts: webserver
  become: yes
  vars:
    repo_url: "https://github.com/Omargazzah02/start-boots.git"
    app_dir: "/home/ubuntu/next-app"
  tasks:
    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: yes

    
    - name: Vérifier si le dossier du projet existe
      stat:
        path: "{{ app_dir }}/.git"
      register: git_repo

    - name: Cloner le projet s'il n'existe pas
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes
      when: not git_repo.stat.exists

    - name: Mettre à jour le projet si déjà cloné
      shell: |
        cd {{ app_dir }}
        git reset --hard
        git pull origin main
      when: git_repo.stat.exists

    - name: Installer les dépendances et builder
      shell: |
        cd {{ app_dir }}
        npm install
        sudo npm i pm2
        npm run build

    - name: Démarrer l’application avec PM2
      shell: |
        cd {{ app_dir }}
        pm2 restart next-app || pm2 start node_modules/next/dist/bin/next --name "next-app" -- start
        pm2 save