name: Deploy Next.js App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Ajouter la clé SSH privée et configurer SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Vérifier la connexion SSH
        run: ssh ubuntu@${{ secrets.REMOTE_HOST }} "echo 'Connexion SSH réussie'"

      - name: Déployer sur le serveur
        run: |
          ssh ubuntu@${{ secrets.REMOTE_HOST }} << 'EOF'
          set -e

          APP_DIR="/home/ubuntu/start-boots"
          REPO_URL="https://github.com/Omargazzah02/start-boots.git"

          echo "Vérification du dossier de l'application..."
          if [ ! -d "$APP_DIR" ]; then
            echo "Le dossier n'existe pas, clonage du projet..."
            git clone $REPO_URL $APP_DIR
          fi

          cd $APP_DIR
          
          echo "Mise à jour du code..."
          git fetch origin main
          git reset --hard origin/main

          echo "Installation des dépendances et build de l'application..."
          npm install
          npm run build

          echo "Démarrage ou redémarrage avec PM2..."
          pm2 describe next-app >/dev/null 2>&1 && pm2 restart next-app || pm2 start npm --name "next-app" -- run start
          pm2 save

          EOF

      - name: Vérifier le déploiement
        run: |
          ssh ubuntu@${{ secrets.REMOTE_HOST }} "curl -I http://localhost:3000"

      - name: Nettoyer la configuration SSH
        run: rm -rf ~/.ssh

      - name: Fin du déploiement
        run: echo "Déploiement terminé avec succès !" 


# 🚨 Assure-toi d'ajouter les secrets nécessaires :
# SSH_PRIVATE_KEY : ta clé SSH privée
# REMOTE_HOST : l'adresse IP ou le domaine de ton serveur

# On est prêt à déployer ! 🚀
